dist: xenial
language: ruby
rvm:
  - 2.3
  - 2.4
  - 2.5
  - 2.6
  - jruby-head

matrix:
  allow_failures:
    - rvm: jruby-head

addons:
  apt:
    packages:
      - texlive-latex-base
      - texlive-latex-recommended
      - texlive-fonts-recommended
      - texlive-latex-extra

before_install:
  - gem install rake
  - gem install minitest stringex
  - gem install rouge
  - wget https://github.com/htacg/tidy-html5/releases/download/5.4.0/tidy-5.4.0-64bit.deb
  - sudo apt purge libtidy tidy
  - sudo dpkg -i tidy-5.4.0-64bit.deb

script: ruby -Ilib:test test/test_*
